### ISSUE TITLE
Path components should be links

### ISSUE THREAD

**Issue by jbenet** [ipfs/dir-index-html#2]
The path components should be links

![](http://gateway.ipfs.io/ipfs/QmSNtHnRxSnmJCZuHPgXT9ivBSB9dTjgFKg4B18xsYKtUN/cap.png)

**Comment by jessicaschilling** [comment]
(see screenshot: https://gateway.ipfs.io/ipfs/QmSNtHnRxSnmJCZuHPgXT9ivBSB9dTjgFKg4B18xsYKtUN/cap.png)

**Comment by jessicaschilling** [comment]
Current status: this one's partially fixed in that what's after "index of" is a link. But, it's just one link; you can't click on the individual parts between directory slashes to effectively move up and down the tree.
![image](https://user-images.githubusercontent.com/1507828/80009382-35b8a980-8486-11ea-9fb1-364d578754c7.png)

**Comment by Stebalien** [comment]
@jessicaschilling I think that's just ipfs-companion linkifying it for you.

**Comment by jessicaschilling** [comment]
Drat, you're right. (In any case -- the screenshot illustrates what the links should look like.)

**Comment by jessicaschilling** [comment]
Closing this one in favor of the combined dir-index-html UI bounty issue here: https://github.com/ipfs/dir-index-html/issues/37
